{
 "title": "AxeOS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "Hostname", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "axe_uptime{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hash Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_hash_rate{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_temp{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_fan_speed_percent{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speed RPM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_fan_speed_rpm{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Hash",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "axe_hash_rate{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Best Difficulty",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "axe_best_difficulty{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Since boot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "axe_best_session_difficulty{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "axe_uptime{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_uptime{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hash Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    { "expr": "axe_hash_rate", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Hash Rate",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    { "expr": "axe_hash_rate", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Pool",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "axe_stratum_url{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WIFI Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "axe_wifi_status{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shares",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "axe_shares_accepted{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_shares_rejected{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_frequency{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_asic_core_voltage_setting{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_voltage{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_power{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "axe_temp", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "axe_temp", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Asic Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_asic_core_voltage{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_current{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VR Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_vr_temp{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overheated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axe_overheat_mode{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speed (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "axe_fan_speed_rpm", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "J/Th" } },
   "targets": [
    {
     "expr": "(axe_power / axe_hash_rate) * 1000\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg_over_time(axe_power[1m])", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    { "expr": "axe_voltage", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Asic Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    { "expr": "axe_asic_core_voltage", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    { "expr": "axe_current", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Free Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "axe_free_heap", "legendFormat": "{{hostname}}" }
   ]
  }
 ]
}